### ISSUE TITLE
NavigatorHelper  onSelected &onDeselected 多次调用

### ISSUE THREAD

**Issue by lsp19880926** [hackware1993/MagicIndicator#1]
请问一下 NavigatorHelper 中的mNavigatorScrollListener.onSelected(safePosition);  和mNavigatorScrollListener.onDeselected(i);可以去掉么？在onPageSelected中已经调用过。

**Comment by hackware1993** [comment]
不能去掉的，这是为了保证在极端情况下指示器的显示状态正确，比如：你的指示器是可编辑的，显示在A界面，你在B界面编辑了指示器并返回到A界面（你可以想象一下今日头条的频道编辑），此时，原有的PositionData肯定不合法了，如果在合法的PositionData再次生成之前收到了onPageSelect或是onPageScroll回调，这时候去处理就显得没意义。所以我在CommonNavigator.preparePositioinData中去手动调了这三个回调，确保状态正确。同时，如果你当前位于ViewPager的C页，你调用ViewPager.setCurrentItem(C)是不会收到onPageSelected回调的，只会收到onPageScroll(C,0.0f,0)，此时我也将这个处理成onPageSelect，也是为了确保状态正确

**Comment by lsp19880926** [comment]
噢。。这样啊，我这边是在onPageSlect里对文字大小颜色做了改变，导致了 标题会在多次调用的时候闪烁。

**Comment by hackware1993** [comment]
改字体大小确实有问题，主要是内部没保存哪些Item该调用onDeselected，所以每次都循环调用，后面会做个记录，只对需要调用onDeselected的item调用

**Comment by hackware1993** [comment]
@lsp19880926  这个问题已解决，你再试试改变字体大小

**Comment by KylinTian** [comment]
compile 'com.github.hackware1993:MagicIndicator:1.5.0'
这个版本，问题还是存在的
onPageSelected()方法循环调用，形成死循环

**Comment by yizuochengchi** [comment]
implementation 'com.yarolegovich:discrete-scrollview:1.4.9'  一样遇到这个问题  please fix it,thanks~  @hackware1993
