### ISSUE TITLE
如何设置两个tab之间的间距

### ISSUE THREAD

**Issue by chenwulue** [hackware1993/MagicIndicator#10]
只找到`commonNavigator.setLeftPadding` 和`  commonNavigator.setRightPadding`
请问如何设置两个tab之间的间距呢

**Comment by chenwulue** [comment]
通过设置SimplePagerTitleView的padding来实现了，同时我觉得这个功能比较常用呢，要是能加入到CommonNavigator的api里面进去就更好了

**Comment by hackware1993** [comment]
@chenwulue 你参考demo中的fixedtabexampleactivity的最后一个效果，通过给LinearLayout设置分割线来设置tab间的间距
