### ISSUE TITLE
可不可以直接设置一个图片作为指示器 那样就可以不管是三角形或者圆形 直线 

### ISSUE THREAD

**Issue by Chan911** [hackware1993/MagicIndicator#11]
比如今天要下滑指示器是一个小圆点 明天改成三角形 后天换成心形了。。。 可不可以不论换成什么样式的指示器 只要UI给一个切图 直接设置图片作为指示器 那就近乎万能的了
或者加一个这样的指示器，因为这种的现在也比较常见：https://cloud.githubusercontent.com/assets/20198975/19397475/9a55be8e-927a-11e6-8f14-eb81c2c1b722.png 我就简单描述一下 就是一个直线，直线中间是个实心的三角形，我看目前是支持三角形的指示器，但是这个三角形指示器只有一个三角形，下面的直线没有了，或者说就是项目里的第九个指示器，但是下面的那个直线不是连在一起的，而是跟别的指示器一样和tab文字一起的

还有一种指示器也比较常见：
https://cloud.githubusercontent.com/assets/20198975/19397577/f81b074a-927a-11e6-91e6-eb01964f4eb2.png
就是一般的指示器是在文字下方一条直线，可不可以文字上方和下方都有一条直线呢
非常期待您能够实现

**Comment by hackware1993** [comment]
@Chan911 内置的效果只照顾最通用的效果，你说的这两种效果我见得很少，不过可以继承IPagerIndicator来实现，很简单

**Comment by JiaZIcheng** [comment]
class BitmapIndicator(context: Context, private val bitmap:Bitmap) : LinePagerIndicator(context){
    val rect = Rect()
    override fun onDraw(canvas: Canvas) {
        val parentClass: Class<*> = LinePagerIndicator::class.java
        val privateField: Field = parentClass.getDeclaredField("mLineRect")
        privateField.isAccessible = true
        val value = privateField.get(this) as RectF
        val bottom = value.bottom.toInt()
        val top = bottom - bitmap.height
        val left = value.centerX().toInt() - bitmap.width/2
        val right = value.centerX().toInt() + bitmap.width/2
        rect.set(left,top,right,bottom)
        canvas.drawBitmap(bitmap,null,rect,null)
    }
}

**Comment by JiaZIcheng** [comment]
`class BitmapIndicator(context: Context, private val bitmap:Bitmap) : LinePagerIndicator(context){
    val rect = Rect()
    override fun onDraw(canvas: Canvas) {
        val parentClass: Class<*> = LinePagerIndicator::class.java
        val privateField: Field = parentClass.getDeclaredField("mLineRect")
        privateField.isAccessible = true
        val value = privateField.get(this) as RectF
        val bottom = value.bottom.toInt()
        val top = bottom - bitmap.height
        val left = value.centerX().toInt() - bitmap.width/2
        val right = value.centerX().toInt() + bitmap.width/2
        rect.set(left,top,right,bottom)
        canvas.drawBitmap(bitmap,null,rect,null)
    }
}`

**Comment by JiaZIcheng** [comment]
class BitmapIndicator(context: Context, private val bitmap:Bitmap) : LinePagerIndicator(context){
    val rect = Rect()
    override fun onDraw(canvas: Canvas) {
        val parentClass: Class<*> = LinePagerIndicator::class.java
        val privateField: Field = parentClass.getDeclaredField("mLineRect")
        privateField.isAccessible = true
        val value = privateField.get(this) as RectF
        val bottom = value.bottom.toInt()
        val top = bottom - bitmap.height
        val left = value.centerX().toInt() - bitmap.width/2
        val right = value.centerX().toInt() + bitmap.width/2
        rect.set(left,top,right,bottom)
        canvas.drawBitmap(bitmap,null,rect,null)
    }
}
