### ISSUE TITLE
如果只有2个tab的话，怎么让这两个tab在各自在左或者在右边居中？

### ISSUE THREAD

**Issue by BeforeFuture** [hackware1993/MagicIndicator#110]
如果只有2个tab的话，怎么让这两个tab在各自在左（ 另一个在右边）居中？
现在的问题是，如果只有两个tab、我设置了居中，这俩个tab的标题挨在一起，在标题栏的最中央了。

**Comment by luyun181** [comment]
这个问题解决？应该怎么做啊？

**Comment by BilalAsif25** [comment]
Please tell how to solve this issue

**Comment by RFlame** [comment]
[可以在getTitleView中设置TitleView的宽度
![EA39192E-C97C-4d6b-AC81-DDE278B42987](https://user-images.githubusercontent.com/9443644/59586744-33731980-9116-11e9-9bab-857b41c1825f.png)

**Comment by qianshengta** [comment]
请问有解决办法吗？我需要两个空间居中显示，中间可以控制的间隔？
