### ISSUE TITLE
Title设置Gravity不起作用

### ISSUE THREAD

**Issue by fshlny** [hackware1993/MagicIndicator#119]
public class PagerTitle extends ColorTransitionPagerTitleView {
    public PagerTitle(Context context) {
        super(context);
        setGravity(Gravity.LEFT);
    }
最终显示的标题还是按照居中显示

**Comment by fairytale110** [comment]
查看sample里面的ScaleTransitionPagerTitleView示例，你会发现，onEnter和onLeave，进行了缩放，选中那个titleView才是实际尺寸样式，未选中那些都是缩小后的效果，所以你设置setGravity是无效的，

我的需求是要底部对齐，当时琢磨了很久，给你指点下，查查ScaleTransitionPagerTitleView里那个setScaleX 和setScaleY 方法的实现逻辑和原理，你就知道怎么改了。
