### ISSUE TITLE
关于选中项字体的变化

### ISSUE THREAD

**Issue by lvzhanlong** [hackware1993/MagicIndicator#13]
如何设置标题选中与未选中的字体大小

**Comment by 452MJ** [comment]
OnPagerTitleChangeListener.onSelected和OnPagerTitleChangeListener.onDeselected自己设置

**Comment by lvzhanlong** [comment]
哪个类的方法

**Comment by 452MJ** [comment]
CommonPagerTitleView.setOnPagerTitleChangeListener(new CommonPagerTitleView.OnPagerTitleChangeListener() {
                    @Override
                    public void onSelected(int i, int i1) {
                        //你要的选中效果
                    }

                    @Override
                    public void onDeselected(int i, int i1) {
                        //你要的选中效果
                    }

                    @Override
                    public void onLeave(int i, int i1, float v, boolean b) {

                    }

                    @Override
                    public void onEnter(int i, int i1, float v, boolean b) {

                    }
                });

**Comment by lvzhanlong** [comment]
怎么同时设置颜色的变化和字体大小的变化

**Comment by hackware1993** [comment]
![image](https://cloud.githubusercontent.com/assets/6748135/19672183/d54407c4-9aa6-11e6-8708-021c0be8823a.png)

**Comment by hackware1993** [comment]
@lvzhanlong 如果要同时设置字体大小和颜色的话，可以继承ColorTransitionPagerTitleView，再更改字体大小

**Comment by lvzhanlong** [comment]
@hackware1993 明白了

**Comment by lvzhanlong** [comment]
整个indicator是上下自带间距的，是否有现成的方法可以调整这个间距
