### ISSUE TITLE
Indicator第一次不能正常滑动?

### ISSUE THREAD

**Issue by 452MJ** [hackware1993/MagicIndicator#14]
![123](https://cloud.githubusercontent.com/assets/13673008/19962392/56664cc0-a1f2-11e6-85c3-c7a4c8efc207.png)

初始化刚进入页面的时候，Indicator不能正常滑动，一定要选择手动点击或者滑动Viewpager选择其他页面后，才能正常滑动Indicator。

Fragment代码：https://github.com/452MJ/C9MJ/blob/master/app/src/main/java/com/c9mj/platform/explore/ui/ExploreFragment.java

布局XML代码：https://github.com/452MJ/C9MJ/blob/master/app/src/main/res/layout/fragment_explore.xml

不知道有没有设置错东西

**Comment by 452MJ** [comment]
一直会跳会第一个Fragment。只有点击到其他Fragment时才能正常滑动

**Comment by 452MJ** [comment]
可以下载调试看看

**Comment by 452MJ** [comment]
我把自己的 CommonPagerTitleView自定义布局代码替换了Demo中ScrollableTabExampleActivity的initMagicIndicator2()中SimplePagerTitleView。发现刚进去也不能正常滑动。CommonPagerTitleView自定义布局中有个bug吧？

**Comment by 452MJ** [comment]
出现Bug的gif图，比较直观。
[https://github.com/452MJ/C9MJ/blob/master/screenshots/bug.gif](url)
![bug](https://github.com/452MJ/C9MJ/blob/master/screenshots/bug.gif)

**Comment by 452MJ** [comment]
navigator.setSkimOver(true);
加上这句就好了=。=这行代码是什么含义

**Comment by 452MJ** [comment]
navigator.setSkimOver(true);
只有用于ClipPagerTitleView才有作用。
CommonPagerTitleView还是不行。

**Comment by hackware1993** [comment]
你是在虚拟机上不能滑动么？以真机为准，我马上下载你的跑马跑一跑

**Comment by hackware1993** [comment]
我在真机上跑了跑，没发现不能滚动的问题。CommonNavigator只是一个HorizontalScrollView + LinearLayout，没有任何理由不滚动啊。对了，你那个RecyclerView的item动画不错！

**Comment by 452MJ** [comment]
`            public IPagerTitleView getTitleView(final Context context, final int index) {
                ClipPagerTitleView titleView = new ClipPagerTitleView(context);
                titleView.setText(titleList.get(index));
                titleView.setBackground(context.getResources().getDrawable(R.drawable.ripple_tab));
                titleView.setTextSize(SizeUtils.sp2px(context, 12));
                titleView.setTextColor(context.getResources().getColor(R.color.color_secondary_text));
                titleView.setClipColor(context.getResources().getColor(R.color.color_primary));
                titleView.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        viewPager.setCurrentItem(index);
                    }
                });
                return titleView;

//                CommonPagerTitleView titleView = new CommonPagerTitleView(context);
//                titleView.setContentView(R.layout.item_explore_tab_indicator_layout);//加载自定义布局作为Tab
//
//                final TextView tab_textview = (TextView) titleView.findViewById(R.id.tab_text);
//                titleView.setOnPagerTitleChangeListener(new CommonPagerTitleView.OnPagerTitleChangeListener() {
//                    @Override
//                    public void onSelected(int i, int i1) {
//                        tab_textview.setText(tnameArray[i]);
//                        tab_textview.setTextColor(context.getResources().getColor(R.color.color_primary));
//                    }
//
//                    @Override
//                    public void onDeselected(int i, int i1) {
//                        tab_textview.setText(tnameArray[i]);
//                        tab_textview.setTextColor(context.getResources().getColor(R.color.color_secondary_text));
//                    }
//
//                    @Override
//                    public void onLeave(int i, int i1, float v, boolean b) {
//
//                    }
//
//                    @Override
//                    public void onEnter(int i, int i1, float v, boolean b) {
//
//                    }
//                });
//                titleView.setOnClickListener(new View.OnClickListener() {
//                    @Override
//                    public void onClick(View v) {
//                        viewPager.setCurrentItem(index);
//                    }
//                });
//                return titleView;
            }`

@hackware1993 可以正常滚动是因为我把CommonPagerTitleView 暂时先注释掉，换成ClipPagerTitleView了，ClipPagerTitleView是正常的，你试下去掉注释换成CommonPagerTitleView 。我的OPPO真机还是不行。

**Comment by 452MJ** [comment]
因为我是想给Tab添加个5.0系统的点击波纹效果，所以才想到用自定义布局。现在折中的处理方法就是ClipPagerTitleView..setBackground(context.getResources().getDrawable(R.drawable.ripple_tab))，自己定义一个ripple.xml来设置背景。

**Comment by hackware1993** [comment]
@452MJ 还是不行么

**Comment by 452MJ** [comment]
@hackware1993 是的。CommonPagerTitleView 依旧不行。你把CommonPagerTitleView 注释去掉尝试下。

**Comment by 452MJ** [comment]
大概知道原因了。如上面CommonPagerTitleView的监听中，onSelected&OnDeselected中setText，貌似会一直使焦点重置在第一个Tab，我把setText提到监听外，就不会有上述的情况。

之前也有使用过在监听中设置setText，不过Tab的数目比较少且固定3-4个，所以一直没有滑动的问题。

**Comment by CK875430315** [comment]
ClipPagerTitleView titleView = new ClipPagerTitleView(context);
                titleView.setText(titleList.get(index));  这里调用了setText（）方法后相应的父类里onSelected 和onDeselected方法里如果也调用了setText方法就会出现这个问题 好像

**Comment by yizuochengchi** [comment]
一样的问题 建议修复 @hackware1993   多谢~

**Comment by yizuochengchi** [comment]
原因 onDeselected onSelected 多次回调 
解决方式 自己维护 list集合加状态  

var curItem: Int = -1 // -1 未选中 0 onDeselected 1 onSelected


建议修复~ 多谢  @hackware1993

**Comment by zzzsssbo** [comment]
怎么解决，我也遇到了这个问题
