### ISSUE TITLE
指示器这个类LinePagerIndicator   后面可以支持图片么？

### ISSUE THREAD

**Issue by xyZangGit** [hackware1993/MagicIndicator#144]
我看到很多人问这个图片的需求，看来大家很多这种效果

**Comment by axepudding** [comment]
这个需求还是有很多的，估计还是得自己写吧。。

**Comment by xyZangGit** [comment]
> 这个需求还是有很多的，估计还是得自己写吧。。

我现在要在下面的指示器为图片应该怎么修改？我看到现在支持的全都是颜色？

**Comment by chenhang19920630** [comment]
可以用图片啊，继承IPagerIndicator，然后自己画你想要的图片就行了

**Comment by chenhang19920630** [comment]
> > 这个需求还是有很多的，估计还是得自己写吧..
> 
> 我现在要在下面的指示器为图片应该怎么修改？我看到现在支持的全都是颜色？
继承IPagerIndicator类，自己画出图片，
关键代码：
![5nwgwklzxa unzil010 5r](https://user-images.githubusercontent.com/20785879/47889689-2dca0b80-de86-11e8-86d3-d6780c66c20e.png)

**Comment by q88qaz** [comment]
没有完整代码？你妈耍猴呢？

**Comment by xyZangGit** [comment]
> 没有完整代码？你妈耍猴呢？

你妈生的孩子没屁眼，祝你永远找不到工作，

**Comment by zhongweihan** [comment]
> 没有完整代码？你妈耍猴呢？

给你这种孤儿玩意完整代码你看得懂吗?回家吃屎去吧

**Comment by junao** [comment]
> 没有完整代码？你妈耍猴呢？

这是个傻逼吗，蠢的理直气壮

**Comment by chenhang19920630** [comment]
> 没有完整代码？你妈耍猴呢？
你但凡好好说话，我就帮你写了

**Comment by PJNB** [comment]
> 没有完整代码？你妈耍猴呢？

这么菜还写个几把代码，我家的狗看了，气的连夜写了好几种类

**Comment by q88qaz** [comment]
急了，这只狗急了

**Comment by JiaZIcheng** [comment]
class BitmapIndicator(context: Context, private val bitmap:Bitmap) : LinePagerIndicator(context){
    val rect = Rect()
    override fun onDraw(canvas: Canvas) {
        val parentClass: Class<*> = LinePagerIndicator::class.java
        val privateField: Field = parentClass.getDeclaredField("mLineRect")
        privateField.isAccessible = true
        val value = privateField.get(this) as RectF
        val bottom = value.bottom.toInt()
        val top = bottom - bitmap.height
        val left = value.centerX().toInt() - bitmap.width/2
        val right = value.centerX().toInt() + bitmap.width/2
        rect.set(left,top,right,bottom)
        canvas.drawBitmap(bitmap,null,rect,null)
    }
}
