### ISSUE TITLE
API 28混淆的时候混淆不通过

### ISSUE THREAD

**Issue by ichapter** [hackware1993/MagicIndicator#148]
Warning: net.lucode.hackware.magicindicator.buildins.commonnavigator.titles.ClipPagerTitleView: can't find referenced method 'int save(int)' in library class android.graphics.Canvas

**Comment by ichapter** [comment]
> #125
我是通过Gradle依赖的，如果导入源码可以按照那样修改的，不过我已经解决这个问题了,tanks

**Comment by billsinla** [comment]
> > #125
> > 我是通过Gradle依赖的，如果导入源码可以按照那样修改的，不过我已经解决这个问题了,tanks

请问你是怎么解决的

**Comment by ichapter** [comment]
@billsinla 我是直接弃用这个库了,并没有拉下源码进行修改

**Comment by billsinla** [comment]
> @billsinla 我是直接弃用这个库了,并没有拉下源码进行修改

我这边弄好了，直接在混淆里面加   -ignorewarnings    就可以了
