### ISSUE TITLE
可以竖着么？

### ISSUE THREAD

**Issue by zengcanxiang** [hackware1993/MagicIndicator#15]
如题，可以设置竖状么？

**Comment by hackware1993** [comment]
@zengcanxiang 这个不计划支持哦，你是要搭配竖向的ViewPager么？

**Comment by zengcanxiang** [comment]
@hackware1993 额，就是简单的竖状的分类，不搭配viewpager

**Comment by hackware1993** [comment]
@zengcanxiang 你的效果是什么样的？能贴个图么？

**Comment by zengcanxiang** [comment]
![qq 20161107130318](https://cloud.githubusercontent.com/assets/16033497/20046970/9bd8db74-a4ea-11e6-9465-5adaf5ed8a4a.png)
类似这样的

**Comment by hackware1993** [comment]
@zengcanxiang 你这个需求貌似不复杂，自己用垂直的LinearLayout写吧

**Comment by zengcanxiang** [comment]
嘿嘿，因为数据和样式和其他的title都一样，就是横竖不一样，我找了一下文档，没有发现能否设置竖的，想问一下。
