### ISSUE TITLE
不维护了吗？AndroidX咋办呢

### ISSUE THREAD

**Issue by xiagea** [hackware1993/MagicIndicator#152]
AndroidX包有问题啊

**Comment by hackware1993** [comment]
维护啊，啥问题？

**Comment by xiagea** [comment]
> 维护啊，啥问题？

升级AndroidX啊

**Comment by egogg** [comment]
<img width="820" alt="screen shot 2018-12-11 at 5 53 58 pm" src="https://user-images.githubusercontent.com/4122475/49792487-d1ec7f80-fd6d-11e8-9ee7-7c290a397d5e.png">

**Comment by AndyAWD** [comment]
Warning: net.lucode.hackware.magicindicator.buildins.commonnavigator.titles.ClipPagerTitleView: can't find referenced method 'int save(int)' in library class android.graphics.Canvas

**Comment by changjianlong** [comment]
老员工用了这个库，我升级androidx也是遇到这个问题，没地办法了，你如果不维护，我就自己搞一下了
