### ISSUE TITLE
如何设置两个title之间的间隔呢？

### ISSUE THREAD

**Issue by zengcanxiang** [hackware1993/MagicIndicator#16]
我想设置title与两边相差一段距离，例如，第一个，indicator的填充不靠边

**Comment by hackware1993** [comment]
@zengcanxiang 能贴个效果图么？

**Comment by zengcanxiang** [comment]
![qq 20161107130525](https://cloud.githubusercontent.com/assets/16033497/20047006/e79bbf2c-a4ea-11e6-8335-3d6d38207aa5.png)

**Comment by hackware1993** [comment]
@zengcanxiang 有两种控制间隔的方式，一种是设置title自身的padding，另一种是给外层的LinearLayout设置divider，前者可能会导致指示线过长，需要结合LinePagerIndicator的setMode和setXOffset做调整，后者请参考demo中的FixedTabExampleActivity的最后一个效果。

**Comment by zengcanxiang** [comment]
@hackware1993 好了，谢谢
