### ISSUE TITLE
想嵌套使用，发现里面的滑动不了，就一个MagicIndicator+Viewpager，然后这个ViewPager里的Fragment再包含一个MagicIndicator+Viewpager

### ISSUE THREAD

**Issue by xiaominglei001** [hackware1993/MagicIndicator#160]
然后，里面的ViewPager左后滑动切换不了，请教该怎么办啊， 谢谢！

**Comment by xuzhiyong017** [comment]
同问

**Comment by youlai** [comment]
同问

**Comment by xiaominglei001** [comment]
> 同问

**Comment by youlai** [comment]
你解决了吗，还是换了别的

**Comment by xiaominglei001** [comment]
作者没回复，说下我的解决方法吧：

在MagicIndicator+Viewpager，然后这个ViewPager里的Fragment不再用MagicIndicator而用下面这个，目前满足我的需求。 
https://github.com/JakeWharton/ViewPagerIndicator

**Comment by xiaominglei001** [comment]
> 你解决了吗，还是换了别的

作者没回复，说下我的解决方法吧：

在MagicIndicator+Viewpager，然后这个ViewPager里的Fragment不再用MagicIndicator而用下面这个，目前满足我的需求。 
https://github.com/JakeWharton/ViewPagerIndicator

**Comment by xiaominglei001** [comment]
> 同问

作者没回复，说下我的解决方法吧：

在MagicIndicator+Viewpager，然后这个ViewPager里的Fragment不再用MagicIndicator而用下面这个，目前满足我的需求。 
https://github.com/JakeWharton/ViewPagerIndicator

**Comment by xiaominglei001** [comment]
就是说，我现在的结构是一个Activity里面是MagicIndicator+Viewpager，Viewpager中是四个Fragment,然后我第二个Frament里用的是ViewPagerIndicator指示器，里面含两个Fragment,目前左右切换滑动正常，满足需求。

**Comment by many-cat** [comment]
参考：https://www.jianshu.com/p/6fe6d613bc01

**Comment by uncleShi** [comment]
将fragment里面的getFragmentManager替换为getChildFragmentManager

**Comment by sing1** [comment]
用viewpager，别用viewpager2
