### ISSUE TITLE
oppo手机滑动bug

### ISSUE THREAD

**Issue by BigSweet** [hackware1993/MagicIndicator#161]
![image](https://user-images.githubusercontent.com/18210031/51735013-2c912f00-20c1-11e9-9717-1f8502fa157a.png)
第一次进入界面的时候滑动(ps:是滑动不是点击)MagicIndicator导致onselect一直触发，这个时候如果在里面做了textview的操作就会导致第一个textview一直聚焦就像这样开始抖动，暂时只在oppo手机上面发现这个问题

![kapture 2019-01-25 at 17 07 38](https://user-images.githubusercontent.com/18210031/51735961-ca85f900-20c3-11e9-9033-12f49769cc8b.gif)

**Comment by BigSweet** [comment]
看源代码是在onlayout中触发了onselect。导致onselect一直触发

**Comment by BigSweet** [comment]
切换tab或者滑动viewpager后bug就消失，只在第一次初始化的时候发生

**Comment by wp549741214** [comment]
同bug。oppo a77手机上。使用CommonPagerTitleView，setContentView  操作内部textview字体加粗问题。
初始化后，出现抖动问题。或者大幅度滑动后，会跳会第一个tab。
切换tab或者滑动viewpager后消失。 app后台，再切回来  也会出现这个问题。

**Comment by hysea** [comment]
> ![image](https://user-images.githubusercontent.com/18210031/51735013-2c912f00-20c1-11e9-9717-1f8502fa157a.png)
> 第一次进入界面的时候滑动(ps:是滑动不是点击)MagicIndicator导致onselect一直触发，这个时候如果在里面做了textview的操作就会导致第一个textview一直聚焦就像这样开始抖动，暂时只在oppo手机上面发现这个问题
> 
> ![kapture 2019-01-25 at 17 07 38](https://user-images.githubusercontent.com/18210031/51735961-ca85f900-20c3-11e9-9033-12f49769cc8b.gif)

请问你这个问题解决了没？

**Comment by xuningForAndroid** [comment]
请问，这个问题如何解决？谢谢

**Comment by spuermax** [comment]
刚解决  ，可以交流交流 。

https://blog.csdn.net/qq_37492806/article/details/103736312

**Comment by BigSweet** [comment]
我这边的解决方法是
首先设置
commonNavigator.setReselectWhenLayout(false)
在手动触发commonNavigator.onPageSelected(tabIndex)
这个tabindex是你进入界面之后默认想滑动到哪个tab，一般都是0
设置好这俩个之后，就不会出现这个bug了
这个bug的原因是，在getTitleView里面的onSelected方法中做了字体的加粗操作。
字体的加粗操作会触发requestlayout，继续触发parent的requestlayout方法，而textview的parent是CommonNavigator,CommonNavigator的layout方法中会触发onPageSelected(mNavigatorHelper.getCurrentIndex());
这样就是一个死循环，不过看代码中发现mReselectWhenLayout属性是可以避免去调用pageselect的，但是需要我们手动去触发
