### ISSUE TITLE
Is there a posibility of filter results from an input string?

### ISSUE THREAD

**Issue by victorjaviermartin** [hackware1993/MagicIndicator#17]
Hi, is there a posibility of filter results from an input string? For example, if I have 8 items, then write "an" in an edittext and there is only one item that it title starts with "an", the result will be only one element.

**Comment by hackware1993** [comment]
@victorjaviermartin sure, please refrence to DynamicTabExampleActivity.java in demo. you can dynamically modify tabs by call CommonNavigator.notifyDataSetChanged().

**Comment by victorjaviermartin** [comment]
Thank you for your info. I didn't see it. Maybe more info into the docs where people could find this things could help? Thank you
