### ISSUE TITLE
How can I set LinePagerIndicator's width 

### ISSUE THREAD

**Issue by ChanBlue** [hackware1993/MagicIndicator#18]
Hi,How can I set LinePagerIndicator's width ? I saw that there are three modes: MODE_EXACTLY,MODE_MATCH_EDGE and MODE_WRAP_CONTENT,but I wanna set it's width between  MODE_WRAP_CONTENT and MODE_MATCH_EDGE,however,MODE_EXACTLY is too short to my requirement,how can I  I set it's width? Thanks!

**Comment by hackware1993** [comment]
@ChanBlue ???

**Comment by ChanBlue** [comment]
I have found that method to set it's width  indicator.setLineWidth(int width).

**Comment by hackware1993** [comment]
@ChanBlue then what?
