### ISSUE TITLE
怎样设置Tab字体加粗呀

### ISSUE THREAD

**Issue by BarefootBKK** [hackware1993/MagicIndicator#181]

**Comment by MhuiHugh** [comment]
可以要继承，加个设置样式的方法

**Comment by maosheng1991** [comment]
ScaleTransitionPagerTitleView 里面添加
 @Override
    public void onSelected(int index, int totalCount) {
        super.onSelected(index, totalCount);
        getPaint().setFakeBoldText(true);
    }

    @Override
    public void onDeselected(int index, int totalCount) {
        super.onDeselected(index, totalCount);
        getPaint().setFakeBoldText(false);
    }

**Comment by BarefootBKK** [comment]
> 
> 
> 可以要继承，加个设置样式的方法
