### ISSUE TITLE
titie中文时，文字没有居中

### ISSUE THREAD

**Issue by chenwulue** [hackware1993/MagicIndicator#20]
使用以下这种样式（TAB WITH BADGE VIEW页面的第三个）
`MagicIndicator magicIndicator = (MagicIndicator) findViewById(R.id.magic_indicator3);
//        magicIndicator.setBackgroundResource(R.drawable.round_indicator_bg);
        CommonNavigator commonNavigator = new CommonNavigator(this);
        commonNavigator.setAdapter(new CommonNavigatorAdapter() {
            @Override
            public int getCount() {
                return mDataList == null ? 0 : mDataList.size();
            }

            @Override
            public IPagerTitleView getTitleView(Context context, final int index) {
                BadgePagerTitleView badgePagerTitleView = new BadgePagerTitleView(context);

                ClipPagerTitleView clipPagerTitleView = new ClipPagerTitleView(context);
                clipPagerTitleView.setText(mDataList.get(index));
                clipPagerTitleView.setTextColor(Color.parseColor("#000000"));//默认文本颜色
                clipPagerTitleView.setClipColor(Color.WHITE);//选中后文本颜色
                clipPagerTitleView.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        mViewPager.setCurrentItem(index);
                    }
                });
                badgePagerTitleView.setInnerPagerTitleView(clipPagerTitleView);

                return badgePagerTitleView;
            }

            @Override
            public IPagerIndicator getIndicator(Context context) {
                LinePagerIndicator indicator = new LinePagerIndicator(context);
                float navigatorHeight = context.getResources().getDimension(R.dimen.common_navigator_height_test);
                float borderWidth = UIUtil.dip2px(context, 1);
                float lineHeight = navigatorHeight - 2 * borderWidth;
                indicator.setLineHeight(lineHeight);
                indicator.setRoundRadius(lineHeight / 2);
                indicator.setYOffset(borderWidth);
                indicator.setColors(Color.parseColor("#f4ac29"));//圆形颜色
                return indicator;
            }
        });
        magicIndicator.setNavigator(commonNavigator);
        ViewPagerHelper.bind(magicIndicator, mViewPager);`

如果text是中文，没有居中。。。

**Comment by hackw** [comment]
@chenwulue 不会吧，很明显么？我这边没问题啊

**Comment by chenwulue** [comment]
很明显，这个样式的会，其它的还没发现

**Comment by hackware1993** [comment]
@chenwulue 你贴个截图看看

**Comment by jack921** [comment]
![Uploading Screenshot_20170407-101926.png…]()
@hackware1993 指示器还是有点不对称，左边多一点右边少一点
