### ISSUE TITLE
MagicIndicator放置在viewpager的fragment下的时候指示器不流畅

### ISSUE THREAD

**Issue by smin9** [hackware1993/MagicIndicator#201]
![image](https://user-images.githubusercontent.com/14284935/62686454-5c69a980-b9f7-11e9-8966-a0eb02b7165e.png)
![Uploading image.png…]()

**Comment by gycold** [comment]
遇到了同样的问题，原因是你没有给fragment设置布局，需要设置好布局

**Comment by smin9** [comment]
额，不是的，我这边是传的FragmentManager传错了，所以滑动卡顿，应该传childFragmentManager。
