### ISSUE TITLE
老哥，你的内存泄漏有点多

### ISSUE THREAD

**Issue by Dboy233** [hackware1993/MagicIndicator#219]
CommonNavigator中的NavigatorHelper会倒是内存泄漏
还有一个内存泄漏没找出来。
老哥优化一下吧。

**Comment by wppwzk** [comment]
他已经创业去当经济学家了，你看看他的博客，已经疯了

**Comment by uncleShi** [comment]
> 他已经创业去当经济学家了，你看看他的博客，已经疯了
我也看到了,惊呆了,我用这个库好久了,作者挺屌的,可惜咋就突然癫狂了呢

**Comment by wppwzk** [comment]
> > 他已经创业去当经济学家了，你看看他的博客，已经疯了
> > 我也看到了,惊呆了,我用这个库好久了,作者挺屌的,可惜咋就突然癫狂了呢

哈哈，疯子不会知道自己是疯子的，他以为别人都疯了
而且把这个聊天还挂到微博上，都没人看，还没有github上看的人多，太搞笑

**Comment by QianHong** [comment]
老哥，快醒醒，你还有个内存泄漏没修复呢？

**Comment by mzhkby** [comment]
@QianHong 问题有解决吗？

**Comment by AndyGu** [comment]
@Dboy233 请问下内存泄露的问题解决了没有，包括您说的没找到的那个问题

**Comment by Dboy233** [comment]
都已经忘了。很久不用这个了。

**Comment by baiyuliang** [comment]
> 他已经创业去当经济学家了，你看看他的博客，已经疯了

博客连接是啥？
