### ISSUE TITLE
如果我是想要平分屏幕宽度应该要怎样做

### ISSUE THREAD

**Issue by zengcanxiang** [hackware1993/MagicIndicator#22]
确定数据不会太多。但是每一份title要在布局所占比例是一样的(不需要上面可以超出屏幕)，应该如果设置。没有找到相关属性，求指点

**Comment by hackware1993** [comment]
@zengcanxiang CommonNavigator.setAdjustMode(true)

**Comment by zengcanxiang** [comment]
谢谢！@hackware1993
