### ISSUE TITLE
如何动态修改tab标题的内容

### ISSUE THREAD

**Issue by flipperji** [hackware1993/MagicIndicator#25]
在fragments里面的一些操作导致标题的内容会有相应的更改，请问有没有相应的方法

**Comment by 452MJ** [comment]
https://github.com/hackware1993/MagicIndicator/blob/master/app/src/main/java/net/lucode/hackware/magicindicatordemo/example/BadgeTabExampleActivity.java
![1](https://cloud.githubusercontent.com/assets/13673008/21837275/c532c2b6-d805-11e6-8b68-c807ba41adae.png)
![2](https://cloud.githubusercontent.com/assets/13673008/21837274/c532b758-d805-11e6-9dde-accd47e5184f.png)

demo里面这个效果应该满足你需要？

**Comment by hackware1993** [comment]
@flipperji 修改数据后调用CommonNavigator.notifyDatasetchanged即可
