### ISSUE TITLE
无法通过gradle引入该库(Unable to resolve dependency for.......1.7.0)

### ISSUE THREAD

**Issue by wangchunfei** [hackware1993/MagicIndicator#257]
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.hackware1993:MagicIndicator:1.7.0.

**Comment by wangchunfei** [comment]
已解决
maven {  url "https://www.jitpack.io" }

**Comment by doulemint** [comment]
有没有其他解决办法，In my case, this solution is not working
