### ISSUE TITLE
和官方的TabLayout冲突了

### ISSUE THREAD

**Issue by ZengHongHua** [hackware1993/MagicIndicator#26]
用了你这个依赖, 然后我项目里,也用了TabLayout, 然后Tablayout会报错,.  

和TabLayout一样,就是一定要和ViewPager一起用,才能起到选择标签的效果, 

单独使用选不到指定的位置,  有什么方法做到不和ViewPager一起也能用吗

**Comment by 452MJ** [comment]
https://github.com/hackware1993/MagicIndicator/blob/master/app/src/main/java/net/lucode/hackware/magicindicatordemo/example/FragmentContainerExampleActivity.java

mFramentContainerHelper = new FragmentContainerHelper(magicIndicator);
mFragmentContainerHelper.handlePageSelected(pageIndex);   // invoke when switch Fragment想选定的时候自己调用这行

**Comment by hackware1993** [comment]
@ZengHongHua 和TabLayout冲突？啥情况
