### ISSUE TITLE
1.7.0  MagicIndicator 与viewpager2联用不能点击

### ISSUE THREAD

**Issue by wuh876** [hackware1993/MagicIndicator#282]
1.7.0  MagicIndicator 与viewpager2联用不能点击

**Comment by Lans** [comment]
老哥，咋解决的

**Comment by wuh876** [comment]
需要给titleview设置点击

**Comment by Lans** [comment]
`            override fun getTitleView(context: Context?, index: Int): IPagerTitleView {
                return CommonPagerTitleView(requireContext())
.apply {
                    // TODO: 标题设置
                    text = "test"
                    setNormalColor(ColorUtils.getColor(R.color.base_colorGray))
                    setSelectedColor(ColorUtils.getColor(R.color.base_colorWhite))
                    setSelectedBackground(R.drawable.shape_round_select)
                    setNormalBackground(R.drawable.shape_round_normal)
                    setNormalSize(16)
                    setSelectedSize(16)
                    setOnClickListener {
                        toast("哈哈$index")
                    }
                }
            }`
好像也不起作用😅

**Comment by Lans** [comment]
没反应的

**Comment by wuh876** [comment]
不会吧，点击事件都没了？

**Comment by Lans** [comment]
我写的有问题，fragment盖在上面了😂，解决了呢

发自Lans
