### ISSUE TITLE
样式这么多却不支持自定义 指示器布局，那么问题来了

### ISSUE THREAD

**Issue by qssq666123** [hackware1993/MagicIndicator#32]
指示器圆角 边框线单独设置颜色 中间是纯白色， 应该怎么绘制？

**Comment by qssq666123** [comment]
扩展性不好，对于只会写布局 样式的小白来说 ，一个实心白色 边框线指示器都不知道该如何改造实现 不支持warp_content 会导致整个屏幕都被这家伙占据了。 如果写死高度则如果太小贝压扁了，

**Comment by qssq666123** [comment]
问题2 、通过直接设置指示器背景颜色，我发现 我发现指示器是居下 的 。并非垂直居中。

**Comment by qssq666123** [comment]
绘制空心的 已解决，我绘制这方面太烂了。后面的问题希望能改进

**Comment by qssq666123** [comment]
空心的宽度又有毛病

**Comment by qssq666123** [comment]
加宽画笔的宽度又导致边界被压缩。。无语了

**Comment by qssq666123** [comment]
希望弄一个 布局方式的扩展 谢谢  感觉在这样我只能放弃了

**Comment by hazyrain** [comment]
我记得有相关扩展的  作者都把怎么自定义都交了。。 你不看博客的？

**Comment by qssq666123** [comment]
@hazyrain 没那么简单，大概看了下 很麻烦，现在的空心椭圆首先是边界被压缩了一个像素，另外他那个实心椭圆其实写的就不太准。。感觉指示器也就那么几种 底部，实心包裹，只要实现了自定义2中样式 其他基于布局 ，我觉得也许一切都简单了。 现在感觉想扩展  学习成本太高。

**Comment by qssq666123** [comment]
@hazyrain  最无奈的莫过于高度问题了，必须写死，看demo都市这样必须写死

**Comment by hackware1993** [comment]
@qssq666123 贴一个你的效果图我看看哈

**Comment by qssq666123** [comment]
https://share.weiyun.com/b5ebc2dc9656392e80a4a527656fece2 如图，高度难调，偏移难弄，实在不知道怎么绘制 怎么算高度。图上其实左边被切掉了一部分
