### ISSUE TITLE
设置指示器与文字之间的间隔

### ISSUE THREAD

**Issue by Yanqilong** [hackware1993/MagicIndicator#41]
可以设置文字到指示器之间的间隔吗？

**Comment by hackware1993** [comment]
你想实现的效果是啥样的？贴一下

**Comment by hackware1993** [comment]
@Yanqilong 参考demo吧

**Comment by SomnusWu** [comment]
![tim 20170921104818](https://user-images.githubusercontent.com/7221064/30676787-78e100f4-9eba-11e7-9b7d-e83f732174f2.png)
 就如这个界面，文字和指示器的距离 ，指示器距离文字xxDp,距离下边距xxDp.

**Comment by SomnusWu** [comment]
![s](https://user-images.githubusercontent.com/7221064/30676942-6ec889e2-9ebb-11e7-9590-f466ca00b1c4.png)

**Comment by hackware1993** [comment]
@SomnusWu lineIndicator.setYOffset.....
