### ISSUE TITLE
你好  ，我是个菜鸟

### ISSUE THREAD

**Issue by yangruixiang** [hackware1993/MagicIndicator#46]
我现在项目需要你这个框架 ，但是现实的是几个fragment，我看您的adapter，是textview，我不知道怎样才能改成fragment，麻烦你说下

**Comment by FollowMountain** [comment]
那就赶紧的看书嘛  ，先把基本的东西搞明白。 你这问题问得别人只能手把手教你写代码了~ 
如果着急做功能    那就看看viewpager、数据适配器是怎么用的
