### ISSUE TITLE
跨多页面滑动时，如何让指示器的滑动速度变慢？

### ISSUE THREAD

**Issue by Noah1991** [hackware1993/MagicIndicator#48]
需要的效果是：你点击指示器，比如从1跳到4，指示器会将4的title置于屏幕中间位置，滑动的速度太快，如何让他变慢，不要让过程一闪而过；效果类似映客首页页签那样！

**Comment by hackware1993** [comment]
你是用的 ViewPager 么？

**Comment by hackware1993** [comment]
如果你使用FragmentContainerHelper，是可以变慢速度的，使用ViewPager则不行
