### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by heygays** [hackware1993/MagicIndicator#5]
WrapPagerIndicator指示器可以加个描边，我在代码中已经修改了，但是下次你更新的时候希望能加上。…^_^
  public void setStrokeColor(int strokeColor) {
        mStrokeColor = strokeColor;
        storkePaint = new Paint(Paint.ANTI_ALIAS_FLAG);
        storkePaint.setStyle(Paint.Style.STROKE);
        storkePaint.setColor(mStrokeColor);
        storkePaint.setStrokeWidth(1);
    }

**Comment by hackware1993** [comment]
额，你可以提个pull request

**Comment by hackware1993** [comment]
@heygays 额，你可以提个pull request

**Comment by hackware1993** [comment]
@heygays 我提供了getPaint方法，就是为了方便外部自定义效果
