### ISSUE TITLE
使用的时候不结合Fragment和ViewPager使用,只是普通的点击tab来改变数据时, 该如何实现,类似于setCurrent()的功能

### ISSUE THREAD

**Issue by hexianqiao3755** [hackware1993/MagicIndicator#57]

**Comment by hackware1993** [comment]
@hexianqiao3755 使用 FragmentContainerHelper，参考 demo 下的 FragmentContainerExampleACtivity

**Comment by hexianqiao3755** [comment]
@hackware1993 谢谢

**Comment by greatflag** [comment]
一楼的意思应该是只用tab切换的效果，但是内容容器不用viewpager或者fragment，应该是直接隐藏或者显示某个VIEW。

**Comment by greatflag** [comment]
看了下源码FragmentContainerHelper不是需要配合Fragment使用的，这个类就是用来控制指示器状态的。可以单独使用，一楼是以为FragmentContainerHelper和Fragment组合使用。。。
