### ISSUE TITLE
请问单独使用Fragment时，如何使用onPageXXX  来得到平滑过渡的效果？

### ISSUE THREAD

**Issue by huangzhongxin** [hackware1993/MagicIndicator#58]

**Comment by hackware1993** [comment]
@huangzhongxin  使用 FragmentContainerHelper，参考 demo 下的 FragmentContainerExampleACtivity

**Comment by huangzhongxin** [comment]
谢谢😄，我按照Demo里能够实现点击那个Tab的文字实现切换了，但是该如何实现左右滑动屏幕达到切换的效果？Demo里面好像没看到？
