### ISSUE TITLE
不结合ViewPager与Fragment使用，控件耦合了这两个类

### ISSUE THREAD

**Issue by HelloLollipop** [hackware1993/MagicIndicator#59]
我的需求是，头部点击切换，下方是一个列表，只针对这一个列表进行刷新，不需要结合ViewPager与Fragment

作者的控件必须要用这两者之一

**Comment by hackware1993** [comment]
@HelloLollipop 非也，这个控件你想用在哪儿都行，跟 ViewPager 和 Fragment 没有强绑定关系

**Comment by HelloLollipop** [comment]
@hackware1993 我看了demo，ViewPager 和 Fragment必须要绑定一个
我头部是一个tablayout，底部只有一个ListView，每一次点击不同的tab去刷新列表。

**Comment by hackware1993** [comment]
@HelloLollipop 你显然没好好看Demo

**Comment by hackware1993** [comment]
@HelloLollipop 你看看 FragmentContainerHelper 就知道了

**Comment by HelloLollipop** [comment]
看过了，已经自己封装了自定义的tablayout

**Comment by CK875430315** [comment]
在指示器的文本点击事件中注释掉  mViewPager.setCurrentItem(index);后切换就失效了，很明显
