### ISSUE TITLE
两次选中跨度比较大时，动画有问题

### ISSUE THREAD

**Issue by wurensen** [hackware1993/MagicIndicator#64]
- 两次选中跨度比较大时，比如有10个title，选中第一个，滑动到最后一个，选中最后一个，此时title会重新走一次动画过来，应该是只有下面指示器做动画会好点

**Comment by wurensen** [comment]
用的CommonNavigator，看了下代码，找到原因了：
`
@Override
    public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
        if (mAdapter != null) {

            mNavigatorHelper.onPageScrolled(position, positionOffset, positionOffsetPixels);
            if (mIndicator != null) {
                mIndicator.onPageScrolled(position, positionOffset, positionOffsetPixels);
            }

            // 手指跟随滚动
            if (mScrollView != null && mPositionDataList.size() > 0 && position >= 0 && position < mPositionDataList.size()) {
                if (mFollowTouch) {
                    int currentPosition = Math.min(mPositionDataList.size() - 1, position);
                    int nextPosition = Math.min(mPositionDataList.size() - 1, position + 1);
                    PositionData current = mPositionDataList.get(currentPosition);
                    PositionData next = mPositionDataList.get(nextPosition);
                    float scrollTo = current.horizontalCenter() - mScrollView.getWidth() * mScrollPivotX;
                    float nextScrollTo = next.horizontalCenter() - mScrollView.getWidth() * mScrollPivotX;
                    mScrollView.scrollTo((int) (scrollTo + (nextScrollTo - scrollTo) * positionOffset), 0);
                } else if (!mEnablePivotScroll) {
                    // TODO 实现待选中项完全显示出来
                }
            }
        }
    }
`
相当于虽然即将选中的item已经可见，可还是会从上一次选中到该次选中做属性动画变化~感觉可以优化，如果当前要选中的项已经可见，不需要从上一次选中做动画过来，不然体验不好。

**Comment by hackware1993** [comment]
@wurensen CommonNavigator.setSkimOver(false)

**Comment by wurensen** [comment]
@hackware1993 能看清楚描述吗？我指的是TitleView，你可以自己用demo看现象。况且skimOver默认就是false

**Comment by nangongkuo** [comment]
我也遇到了这个问题，请问你是怎么解决的？

**Comment by wurensen** [comment]
@nangongkuo 自己修改实现

**Comment by nangongkuo** [comment]
怎么修改的？能贴下代码吗？
