### ISSUE TITLE
请问如果只有两个或者三个tab，并且还要有动画效果的，怎么让他们居中显示

### ISSUE THREAD

**Issue by Cashdispenser** [hackware1993/MagicIndicator#67]
![1](https://user-images.githubusercontent.com/26020575/29655435-a5009f42-88e3-11e7-9c51-55860e5280d1.png)

**Comment by hackware1993** [comment]
@Cashdispenser 参考demo下的 FixedTabExampleActivity

**Comment by Cashdispenser** [comment]
已找到，谢谢楼主
