### ISSUE TITLE
请问这种效果能否实现

### ISSUE THREAD

**Issue by linfeizheng** [hackware1993/MagicIndicator#68]
![wx20170824-163630](https://user-images.githubusercontent.com/9878167/29657489-65dd1ea6-88ea-11e7-885e-d611e9506014.png)
2个tab，分别显示在页面的1/4和3/4处，望解答能否实现

**Comment by hackware1993** [comment]
@linfeizheng 可以

**Comment by linfeizheng** [comment]
额，咋实现呢，因为demo里我没有找到(>_<)

**Comment by linfeizheng** [comment]
找到了，谢谢
