### ISSUE TITLE
请问，只有关联ViewPager才能使用Indecator？

### ISSUE THREAD

**Issue by 452MJ** [hackware1993/MagicIndicator#7]
我可不可以在自定义的BottomBar（类似微信导航栏)，点击的时候也有相应的动画效果，切换FragmentContainerLayout里面的Fragment呢？
不执行关联代码：
 SimpleViewPagerDelegate.with(magicIndicator, viewPager).delegate();

**Comment by hackware1993** [comment]
@452MJ 现在只支持viewpager，你要的特性已经在开发中，实现一个新的delegate，不断分发onPageXXX系列回调即可，敬请期待

**Comment by 452MJ** [comment]
谢谢，辛苦了~~

**Comment by hackware1993** [comment]
@452MJ 现在支持在FragmentContainer中使用啦，你参考demo中第四个效果吧
