### ISSUE TITLE
CommonNavigator.setIndicatorOnTop(true);

### ISSUE THREAD

**Issue by 452MJ** [hackware1993/MagicIndicator#8]
我想测试下把Indicator置于OnTop，设置了下面代码，但是没效果，indicator还是在底部。
CommonNavigator.setIndicatorOnTop(true);

是否还差点什么吗？

**Comment by hackware1993** [comment]
@452MJ 你要的效果应该是indicator.setYOffset，indicatorOnTop是将指示器的层次置于title之上，适用于title本身带背景的情况

**Comment by 452MJ** [comment]
OKOK，我看方法名直接以为是置顶部了。3Q~
