### ISSUE TITLE
有個比較複雜的需求，想請教一下是否能實現。

### ISSUE THREAD

**Issue by lsw19921030** [hackware1993/MagicIndicator#80]
因為對你的庫理解不夠深入，感覺很靈活的樣子，但又想不到應該怎麼做。想請教一下是否可以實現以下需求（需要改庫的話也可以）：

某個Activity有4個Fragment，其中一個Fragment有些時候會disable。Disable時的狀態如下：
1) 這個Indicator依然存在（可視）
2) 這個Indicator alpha 變成 0.4f，並且不可以點擊
3) Scroll時會跳過這個Fragment。

為了簡化，可以假設這個被Disable的Fragment不會是第一或最後一個。也不需要阻止這個Fragment的Initialization（只要不被用戶看到就行）。

我覺得1和2應該都不難，但想不到3可以怎麼做。請問可以指條明路嗎？萬分感謝！

**Comment by hackware1993** [comment]
@lsw19921030 你用了ViewPager么？

**Comment by lsw19921030** [comment]
是的

**Comment by lsw19921030** [comment]
我目前想到的是，ViewPager getCount 返回3，但CommonNavigator的getCount返回4。
但就是想不到怎麼讓ViewPager在scroll到3的時候, 告訴CommonNavigator現在是4

或許你知道要override哪個method?

**Comment by lsw19921030** [comment]
再update一下我的進度：

目前已經很接近效果了，我用了自己的viewPager.addOnPageChangeListener:
        viewPager.addOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
                int realPosition = position;
                if (position == disabledPosition) realPosition = recalculateNextPagePosition(position);
                tabLayout.onPageScrolled(realPosition, positionOffset, positionOffsetPixels);
            }

            @Override
            public void onPageSelected(int position) {
                previousPosition = currentPosition;
                currentPosition = position;
                tabLayout.onPageSelected(recalculateNextPagePosition(position));
            }

            @Override
            public void onPageScrollStateChanged(int state) {
                tabLayout.onPageScrollStateChanged(state);
            }
        });

但是差一點點的是，indicator會在scroll完全停止後才飛過去後面的item；
或者向左scroll的情景則是一開始就在disable的item開始向左scroll…

**Comment by hackware1993** [comment]
@lsw19921030 MagicIndicator 完全依赖于 onPageXXX 系列回调工作，getCount 的数目一定要和 PageAdapter.getCount 一致。

**Comment by hackware1993** [comment]
@lsw19921030 MagicIndicator 里的 Tab 是可扩展的，我初步估计是可以满足你的需求的，你可以继承某个你想使用的 IPagerTitleView，为它添加 disable 的能力。代码类似下面的：

        class SimplePagerTitleViewEx extends SimplePagerTitleView {
            private boolean mEnable = true;

            public SimplePagerTitleViewEx(Context context) {
                super(context);
            }

            @Override
            public void onSelected(int index, int totalCount) {
                super.onSelected(index, totalCount);
                if (!mEnable) {
                    setTextColor(Color.GRAY);
                }
            }

            @Override
            public void onDeselected(int index, int totalCount) {
                super.onDeselected(index, totalCount);
                if (!mEnable) {
                    setTextColor(Color.GRAY);
                }
            }
        }

**Comment by hackware1993** [comment]
@lsw19921030 你在 CommonNavigatorAdapter.getTitleView 里去决定哪一个 tab 要 disable，如果要动态的 disable 某个 tab，在调用 ViewPager.notifyDatasetChanged 之前，要先调用 CommonNavigatorAdapter.notifyDatasetChanged

**Comment by lsw19921030** [comment]
這個對應需求1和2，我都已經成功了，就是差3而已

**Comment by lsw19921030** [comment]
我已經成功讓Indicator跳過被disabled的item來進行Animation了（Viewpager從2 scroll向3時，Indicator會從2 scroll向4。我是透過修改LinePagerIndicator來達成的），
現在唯一剩下的問題就是，原本已經Animate到4的Indicator，當Animation完結後，會瞬間跳回3。

我猜應該還有一個我不知道的參數決定Indicator靜止時的位置，但明顯不在LinePagerIndicator內，請問你知道在哪裡嗎？

**Comment by lsw19921030** [comment]
大功告成！！！！！！
最後原來是因為不能讓onScrollChange最後一個call變成新position (2)導致最終落點改變。
於是我在onPageScroll加一行
`if (position == disabledPosition) return;`
效果就完美了！

打擾了抱歉，不過希望能給別人做參考。

**Comment by hackware1993** [comment]
@lsw19921030 给我邮箱发个apk让我体验下 cfb1993@163.com
