### ISSUE TITLE
提一点小问题

### ISSUE THREAD

**Issue by longyuan5** [hackware1993/MagicIndicator#85]
承然作者分享精神不错，项目也不错，我看简书作者也写着是间接性完美主义者，但是整个项目通篇很少注释，几乎没有，我不太理解，接口中的方法注释还是有必要写下的，个别属性设置注释也好歹写下，这样别人稍微看下注释，整个项目框架一目了然，方便后来人学习，也符合开源的精神。最后还是很谢谢作者的分享。

**Comment by hackware1993** [comment]
确实少了点
